# Generated by Django 5.1.1 on 2024-11-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_descricao_user_servicos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
